export const LOCATION = {
    GET_CURRENT_LOCATION: 'LOCATION/GET_CURRENT_LOCATION',
}

export const CITIES = {
    GET_CITIES_IN_CIRCLE_WEATHER: 'CITIES/GET_CITIES_IN_CIRCLE_WEATHER',
    GET_CITIES_WEATHER_BY_NAME: 'CITIES/GET_CITIES_WEATHER_BY_NAME',
    SET_CITIES_WEATHER: 'CITIES/SET_CITIES_WEATHER',
    SET_CURRENT_CITY_WEATHER: 'CITIES/SET_CURRENT_CITY_WEATHER',
    SET_WEATHER_YESTERDAY: 'CITIES/SET_WEATHER_YESTERDAY'
}
